name: Build APK

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
          
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "node"
                  cache: "npm"
            - name: Download Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
              
            - name: Check android
              id: check_android
              run: echo "exists=$(if [ -d android ]; then echo true; else echo false; fi)" >> "$GITHUB_ENV"
              
            - name: Add android if android not exist
              if: env.exists == 'false'
              run: npx cap add android

            - name: Sync android
              run: npx cap sync android

            - name: Install Java & Android SDK
              run: |
                  sudo apt-get update
                  sudo apt-get install -y openjdk-21-jdk unzip

                  echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV
                  echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
                  
                  export ANDROID_SDK_ROOT=$HOME/android-sdk
                  export ANDROID_HOME=$ANDROID_SDK_ROOT
                  export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

                  mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
                  
                  curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
                 
                  unzip sdk-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
                  rm sdk-tools.zip

                  mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

                  chmod +x $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager

                  ls -l $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
                  $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --version

                  yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
                  $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-35" "build-tools;34.0.0"

            - name: Ensure Java 21 is Used
              run: |
               echo "JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-amd64" >> $GITHUB_ENV
               echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
               
            - name: Check Java Version
              run: java -version
              
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Build APK
              run: |
                cd android
                ./gradlew assembleDebug
                
            - name: Upload APK Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: app-debug.apk
                  path: android/app/build/outputs/apk/debug/app-debug.apk
