name: Build Capacitor APK

on:
  push:
    branches:
      - main  # Runs on push to main branch (change if needed)
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Web Assets
        run: npm run build

      - name: Install Android SDK & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk android-sdk

      - name: Setup Java & Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Sync Capacitor Android Project
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
