name: Build APK

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
          
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "node"
                  cache: "npm"
            - name: Download Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
              
            - name: Check android
              id: check_android
              run: echo "exists=$(if [ -d android ]; then echo true; else echo false; fi)" >> "$GITHUB_ENV"
              
            - name: Add android if android not exist
              if: env.exists == 'false'
              run: npx cap add android

            - name: Sync android
              run: npx cap sync android

            - name: Download Java JDK
              run: |
                sudo apt-get update
                sudo apt-get install -y openjdk-21-jdk

            - name: Download Android SDK
              run: |
                sudo apt-get android-sdk
                yes | sdkmanager --license
                sdkmanager "plaform-tools" "platform;android-35" "build-tools;34.0.0"

            
