name: Build Capacitor APK

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Web Assets
        run: npm run build

      - name: Install OpenJDK 17
        run: sudo apt-get install -y openjdk-17-jdk

      - name: Install Android Command Line Tools
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;34.0.0"

      - name: Configure Android SDK
        run: echo "sdk.dir=$HOME/Android/Sdk" > android/local.properties

      - name: Make Gradle Executable
        run: chmod +x android/gradlew

      - name: Setup Java & Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Sync Capacitor Android Project
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
